### ISSUE TITLE
Convert application to ES6

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/turtl#20]
## ✅ Task List

- [x] Convert all variables `var` to `let` or `const`.
- [x] Convert all strings that are applicable to `template-literals`.
- [x] Convert all functions that are applicable to `arrow` functions.
- [x] If applicable, use destructuring.
- [x] Make sure all features work as expected.
