### ISSUE TITLE
issue-7-minor-changes-to-ui

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/turtl#22]
## 🕹️ Functionality

Add minor changes to the UI.

## ✅ Task List

- [x] Change the `title` tag to match the app's name.
- [x] Change the cursor to `pointer` when hovering over the `go` button.
- [x] If the stock has already been added to favorites, change button to `Remove from Favorites`.
- [x] Change the color of the navigation link once they are hovered.
